[package]
name = "handlebars-fluent"
version = "0.3.0"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]
edition = "2018"
description = "Handlebars helpers for the Fluent internationalization framework"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/handlebars-fluent/"
repository = "https://github.com/manishearth/handlebars-fluent"
keywords = ["handlebars", "fluent", "internationalization", "localization"]
categories = ["internationalization", "localization", "template-engine"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.0"
lazy_static = "1.4"
fluent = "0.16"
fluent-bundle = "0.11"
fluent-syntax = "0.11"
fluent-langneg = "0.12"
serde_json = "1.0"
unic-langid = { version = "0.8", features = ["macros"] }

[dev-dependencies]
tempfile = "3.3"
